---
- name: Deploy Docker container with HTML Page using Apache
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Install pip 
      become: yes
      apt:
        name: python3-pip  
        state: present

    - name: Install Docker Python module
      pip:
        name: docker

    - name: Create Docker network with docker_network ansible module with required subnet 
      docker_network:
        name: apache_network
        driver: bridge
        ipam_config:

          - subnet: 172.168.10.0/30
            #state: present

    - name: Create Docker container with Apache, pulling latest apache image and expose port 80
      docker_container:
        name: network_container
        image: httpd:latest
        ports:
          - "80:80"
        volumes:
          - /tmp/network:/usr/local/apache2/htdocs
        networks:
          - name: apache_network
       
    - name: Copy HTML file to the host
      copy:
        src: /home/jeevan/project/index.html
        dest: /tmp/network
    
    - name: Retrieving IP for verification
      command: /usr/bin/docker inspect --format="{{'{{'}}range .NetworkSettings.Networks{{'}}'}}{{'{{'}}.IPAddress{{'}}'}}{{'{{'}}end{{'}}'}}" network_container
      register: ip
    
    - name: Inventory update
      blockinfile:
        path: /home/jeevan/project/inventory.txt
        block: |
                #[target]
                #{{ ip.stdout }} ansible_user=root ansible_ssh_pass=root ansible_connection=ssh

    - debug:
        msg: "{{ ip.stdout }}"
